ALTER TABLE enterprises
ADD COLUMN IF NOT EXISTS registry_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS vat_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS enterprise_phone VARCHAR(50);
